import type { Metadata } from "next";
import { Lexend, Geist_Mono, Limelight } from "next/font/google";
import "./globals.css";
import { SurveyProvider } from "@/hooks/useSurvey";

const mainSans = Lexend({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notable = Limelight({
  variable: "--font-header",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mainSans.variable} ${geistMono.variable} ${notable.variable} antialiased font-sans`}
      >
        <SurveyProvider>
          {children}
        </SurveyProvider>

      </body>
    </html>
  );
}
